py_django_poc/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from social import views

urlpatterns = [
    url(r'^$', views.login_view, name='login_view'),
    url(r'^logout', views.logout_view, name='logout_view'),
    url(r'^social/', include('social.urls')),
    url(r'^admin/', admin.site.urls),
]

social/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'process_login', views.process_login, name='process_login'),
    url(r'add_keyword', views.add_keyword, name='add_keyword'),
    url(r'search/(?P<keyword_id>\d+)$', views.search, name='search'),
    url(r'searchresults$', views.searchresults, name='searchresults'),
    url(r'get_searchresults_csv', views.get_searchresults_csv, name='get_searchresults_csv'),
]

social/models.py
from django.conf import settings
from django.db import models
from django_mysql.models import EnumField # http://django-mysql.readthedocs.io/en/latest/model_fields/enum_field.html
from django.db import connection

def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

class Keyword(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    keyword_text = models.CharField(max_length=200)
    last_search_date = models.DateTimeField('last search date', null=True)
    date_added = models.DateTimeField('date added')

class KeywordsInSocialMedia(models.Model):
    keyword = models.ForeignKey(Keyword, on_delete=models.CASCADE)
    social_media_type = EnumField(choices=['twitter', 'reddit'])

class SearchResults(models.Model):
    keyword_in_social_media = models.ForeignKey(KeywordsInSocialMedia, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    link_to_content = models.CharField(max_length=500)
    date_added = models.DateTimeField('date added')

    @staticmethod
    def get_search_results_by_user_id(user_id):

        sql = "SELECT social_searchresults.id, social_searchresults.title, social_searchresults.link_to_content, social_keywordsinsocialmedia.social_media_type, social_searchresults.date_added " \
                "FROM social_searchresults " \
                "JOIN social_keywordsinsocialmedia on social_keywordsinsocialmedia.id = social_searchresults.keyword_in_social_media_id " \
                "JOIN social_keyword ON social_keyword.id = social_keywordsinsocialmedia.keyword_id " \
                "WHERE user_id = %s " \
                "ORDER BY social_searchresults.id desc" % user_id

        cursor = connection.cursor()
        cursor.execute(sql)
        result = dictfetchall(cursor)

        return result

    @staticmethod
    def get_search_results_by_ids_for_user_id(user_id, ids):
        sql = "SELECT social_searchresults.id, social_searchresults.title, social_searchresults.link_to_content, social_keywordsinsocialmedia.social_media_type, social_searchresults.date_added " \
              "FROM social_searchresults " \
              "JOIN social_keywordsinsocialmedia on social_keywordsinsocialmedia.id = social_searchresults.keyword_in_social_media_id " \
              "JOIN social_keyword ON social_keyword.id = social_keywordsinsocialmedia.keyword_id " \
              "WHERE user_id = %s " \
                    "AND social_searchresults.id IN (%s) " \
              "ORDER BY social_searchresults.id desc" % (user_id, ids)

        cursor = connection.cursor()
        cursor.execute(sql)
        result = dictfetchall(cursor)

        return result

social/forms.py
from django import forms

class KeywordsForm(forms.Form):
    keyword = forms.CharField(label='Keyword', max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    reddit = forms.BooleanField(label='Reddit', required=False, initial=True)
    twitter = forms.BooleanField(label='Twitter', required=False, initial=True)

social/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
import csv

from social.models import Keyword, KeywordsInSocialMedia, SearchResults
from django.utils import timezone
from forms import KeywordsForm

from social.libraries import keywordlib
from django.core.mail import EmailMessage

# /social
@login_required(login_url='/')
def index(request):
    form = KeywordsForm(request.POST or None)
    keywords_list = Keyword.objects.filter(user_id=request.user.id).order_by('-date_added')

    context = {
        'keywords_list': keywords_list,
        'form': form
    }

    return render(request, 'social/keywords.html', context)

# /
def login_view(request):
    if request.user.is_authenticated:
        return redirect('index')
    else:
        context = {}
        return render(request, 'social/login.html', context)

# /logout
def logout_view(request):
    logout(request)
    return redirect('login_view')

# /social/process_login
def process_login(request):
    username = request.POST['username']
    password = request.POST['password']

    user = authenticate(username=username, password=password)

    if user is not None:                # user is authenticated
        login(request, user)
        return redirect('index')
    else:                               # did not authenticate
        return redirect('login_view')

# /social/add_keyword
@login_required(login_url='/')
def add_keyword(request):
    form = KeywordsForm(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            keyword_record = Keyword(user_id=request.user.id, keyword_text=request.POST['keyword'], date_added=timezone.now())
            keyword_record.save()

            if request.POST.get('reddit', False):
                reddit_record = KeywordsInSocialMedia(keyword_id=keyword_record.id, social_media_type='reddit')
                reddit_record.save()

            if request.POST.get('twitter', False):
                twitter_record = KeywordsInSocialMedia(keyword_id=keyword_record.id, social_media_type='twitter')
                twitter_record.save()

    return redirect('index')

@login_required(login_url='/')
def search(request, keyword_id):
    keywordlib.search(keyword_id)

    return redirect('index')

@login_required(login_url='/')
def searchresults(request):
    searchresults_list = SearchResults.get_search_results_by_user_id(request.user.id)

    context = {
        'searchresults_list': searchresults_list,
    }

    return render(request, 'social/searchresults.html', context)

@login_required(login_url='/')
def get_searchresults_csv(request):
    ids = request.GET.get('ids', '')

    if len(ids) > 0:
        searchresults_list = SearchResults.get_search_results_by_ids_for_user_id(request.user.id, ids)

        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="searchresults.csv"'

        writer = csv.writer(response)

        writer.writerow(['ID', 'Title', 'Link to Content', 'Social Media Type', 'Date Added'])

        for searchresult in searchresults_list:
            writer.writerow([searchresult['id'], searchresult['title'], searchresult['link_to_content'], searchresult['social_media_type'], searchresult['date_added']])

        email = EmailMessage(
            'Search Results CSV',
            'Search results attached',
            'no-reply@socialmentions.com',
            [request.user.email]
        )

        email.attach('searchresults.csv', response.getvalue(), 'text/csv')
        email.send()

        return response
    else:
        return HttpResponse('No data available to export')

social/templates/social/keywords.html
{% extends "social/master.html" %}

{% block title %}Keywords{% endblock title %}

{% block content %}
    <h4 class="sub-header">Keywords</h4>

    <form action="/social/add_keyword" method="post" class="inline-form">
        {% csrf_token %}

        {{ form.non_field_errors }}
        <div class="form-wrapper-div inline-form">
            {{ form.keyword.errors }}
            <div class="form-group">
                <label for="{{ form.keyword.id_for_label }}">Keyword:</label>
                {{ form.keyword }}
            </div>
            <div class="form-group">
                <label for="{{ form.reddit.id_for_label }}">Reddit:</label>
                {{ form.reddit }}
            </div>
            <div class="form-group">
                <label for="{{ form.twitter.id_for_label }}">Twitter:</label>
                {{ form.twitter }}
            </div>

            <input type="submit" value="Save" class="btn btn-primary btn-sm" />
        </div>

        <div class="results-div">
            {% if keywords_list %}
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Keyword</th>
                            <th>Social Media Sites</th>
                            <th>Last Search Date</th>
                            <th>Search</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for keyword in keywords_list %}
                        <tr>
                            <td>{{ keyword.keyword_text }}</td>
                            <td>
                                {% for keywordsinsocialmedia in keyword.keywordsinsocialmedia_set.all %}
                                    {{ keywordsinsocialmedia.social_media_type|title }}{% if not forloop.last %}, {% endif %}
                                {% endfor %}
                            </td>
                            <td>
                                {{ keyword.last_search_date|default:"" }}
                            </td>
                            <td><a href="/social/search/{{ keyword.id }}" class="btn btn-default btn-sm">Search</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>No keywords have been added yet.</p>
            {% endif %}
        </div>
    </form>
{% endblock content %}

social/templates/social/login.html
{% extends "social/master.html" %}

{% block title %}Login{% endblock title %}

{% block body_header %}
    <div class="row">
        <div class="body-header col-xs-12">
            <h2>Social Media Mentions</h2>
        </div>
    </div>
{% endblock body_header %}

{% block content %}
    <div class="row">
        <div class="col-xs-3">
            <h4>Login</h4>
            <form action="/social/process_login" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">Username:</label>
                    <input type="text" value="" id="username" name="username" class="form-control" />
                </div>
                <div class="form-group">
                    <label for="password">Password:</label>
                    <input type="password" value="" name="password" class="form-control" />
                </div>
                <div>
                    <input type="submit" value="Login" class="btn btn-primary btn-sm" />
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

social/templates/social/master.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}{% endblock title %}
    </title>

    <link href="/static/css/main.css" type="text/css" rel="stylesheet" />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" type="text/javascript"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" type="text/css" rel="stylesheet" />

    {% block js %}{% endblock js %}
</head>
<body>
    <div class="container">
        {% block body_header %}
            <div class="row">
                <div class="body-header col-xs-12">
                    <h2>Social Media Mentions</h2>

                    <div class="menu-options">
                        <div class="menu-option-items">
                            <a href="/social">Keywords</a> | <a href="/social/searchresults">Search Results</a>
                        </div>
                        <div class="menu-option-items logout-wrapper-div">
                            <a href="/logout">Logout</a>
                        </div>
                    </div>
                </div>
            </div>
        {% endblock body_header %}
        {% block content %}{% endblock content %}
    </div>
</body>
</html>

social/templates/social/searchresults.html
{% extends "social/master.html" %}

{% block js %}
    <script src="/static/js/searchresults.js" type="text/javascript"></script>
{% endblock js %}

{% block title %}Search Results{% endblock title %}

{% block content %}
    <h4 class="sub-header">Search Results</h4>

    <a href="#" class="prevent-default" id="btn-select-all-search-results">Select All</a> | <a href="/social/get_searchresults_csv" id="btn-export-csv-search-results">Export to CSV</a>

    <form action="#" class="inline-form">
        {% csrf_token %}

        <div class="results-div">
            {% if searchresults_list %}
                <table class="table table-striped results-table">
                    <thead>
                        <tr>
                            <th>Select</th>
                            <th>Title</th>
                            <th>Link to Content</th>
                            <th>Social Media Type</th>
                            <th>Date Added</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for searchresult in searchresults_list %}
                        <tr>
                            <td>
                                <input type="checkbox" class="search-result-checkbox" data-search-result-id="{{ searchresult.id }}" checked />
                            </td>
                            <td>{{ searchresult.title }}</td>
                            <td>{{ searchresult.link_to_content }}</td>
                            <td>{{ searchresult.social_media_type|title }}</td>
                            <td>{{ searchresult.date_added }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>No search results available yet.</p>
            {% endif %}
        </div>
    </form>
{% endblock content %}